/* 
 * RIDB API
 *
 * The Recreation Information Database (RIDB) provides data resources to citizens, offering a single point of access to information about recreational opportunities nationwide. The RIDB represents an authoritative source of information and services for millions of visitors to federal lands, historic sites, museums, and other attractions/resources. This initiative integrates multiple Federal channels and sources about recreation opportunities into a one-stop, searchable database of recreational areas nationwide.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct FacilityGeojson {
  #[serde(rename = "TYPE")]
  TYPE: Option<String>,
  #[serde(rename = "COORDINATES")]
  COORDINATES: Option<Vec<f64>>
}

impl FacilityGeojson {
  pub fn new() -> FacilityGeojson {
    FacilityGeojson {
      TYPE: None,
      COORDINATES: None
    }
  }

  pub fn set_TYPE(&mut self, TYPE: String) {
    self.TYPE = Some(TYPE);
  }

  pub fn with_TYPE(mut self, TYPE: String) -> FacilityGeojson {
    self.TYPE = Some(TYPE);
    self
  }

  pub fn TYPE(&self) -> Option<&String> {
    self.TYPE.as_ref()
  }

  pub fn reset_TYPE(&mut self) {
    self.TYPE = None;
  }

  pub fn set_COORDINATES(&mut self, COORDINATES: Vec<f64>) {
    self.COORDINATES = Some(COORDINATES);
  }

  pub fn with_COORDINATES(mut self, COORDINATES: Vec<f64>) -> FacilityGeojson {
    self.COORDINATES = Some(COORDINATES);
    self
  }

  pub fn COORDINATES(&self) -> Option<&Vec<f64>> {
    self.COORDINATES.as_ref()
  }

  pub fn reset_COORDINATES(&mut self) {
    self.COORDINATES = None;
  }

}



