/* 
 * RIDB API
 *
 * The Recreation Information Database (RIDB) provides data resources to citizens, offering a single point of access to information about recreational opportunities nationwide. The RIDB represents an authoritative source of information and services for millions of visitors to federal lands, historic sites, museums, and other attractions/resources. This initiative integrates multiple Federal channels and sources about recreation opportunities into a one-stop, searchable database of recreational areas nationwide.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct FacilityAddress {
  #[serde(rename = "FacilityAddressID")]
  facility_address_id: String,
  #[serde(rename = "FacilityID")]
  facility_id: String,
  #[serde(rename = "FacilityAddressType")]
  facility_address_type: String,
  #[serde(rename = "FacilityStreetAddress1")]
  facility_street_address1: String,
  #[serde(rename = "FacilityStreetAddress2")]
  facility_street_address2: String,
  #[serde(rename = "FacilityStreetAddress3")]
  facility_street_address3: String,
  #[serde(rename = "City")]
  city: String,
  #[serde(rename = "PostalCode")]
  postal_code: String,
  #[serde(rename = "AddressStateCode")]
  address_state_code: String,
  #[serde(rename = "AddressCountryCode")]
  address_country_code: String
}

impl FacilityAddress {
  pub fn new(facility_address_id: String, facility_id: String, facility_address_type: String, facility_street_address1: String, facility_street_address2: String, facility_street_address3: String, city: String, postal_code: String, address_state_code: String, address_country_code: String) -> FacilityAddress {
    FacilityAddress {
      facility_address_id: facility_address_id,
      facility_id: facility_id,
      facility_address_type: facility_address_type,
      facility_street_address1: facility_street_address1,
      facility_street_address2: facility_street_address2,
      facility_street_address3: facility_street_address3,
      city: city,
      postal_code: postal_code,
      address_state_code: address_state_code,
      address_country_code: address_country_code
    }
  }

  pub fn set_facility_address_id(&mut self, facility_address_id: String) {
    self.facility_address_id = facility_address_id;
  }

  pub fn with_facility_address_id(mut self, facility_address_id: String) -> FacilityAddress {
    self.facility_address_id = facility_address_id;
    self
  }

  pub fn facility_address_id(&self) -> &String {
    &self.facility_address_id
  }


  pub fn set_facility_id(&mut self, facility_id: String) {
    self.facility_id = facility_id;
  }

  pub fn with_facility_id(mut self, facility_id: String) -> FacilityAddress {
    self.facility_id = facility_id;
    self
  }

  pub fn facility_id(&self) -> &String {
    &self.facility_id
  }


  pub fn set_facility_address_type(&mut self, facility_address_type: String) {
    self.facility_address_type = facility_address_type;
  }

  pub fn with_facility_address_type(mut self, facility_address_type: String) -> FacilityAddress {
    self.facility_address_type = facility_address_type;
    self
  }

  pub fn facility_address_type(&self) -> &String {
    &self.facility_address_type
  }


  pub fn set_facility_street_address1(&mut self, facility_street_address1: String) {
    self.facility_street_address1 = facility_street_address1;
  }

  pub fn with_facility_street_address1(mut self, facility_street_address1: String) -> FacilityAddress {
    self.facility_street_address1 = facility_street_address1;
    self
  }

  pub fn facility_street_address1(&self) -> &String {
    &self.facility_street_address1
  }


  pub fn set_facility_street_address2(&mut self, facility_street_address2: String) {
    self.facility_street_address2 = facility_street_address2;
  }

  pub fn with_facility_street_address2(mut self, facility_street_address2: String) -> FacilityAddress {
    self.facility_street_address2 = facility_street_address2;
    self
  }

  pub fn facility_street_address2(&self) -> &String {
    &self.facility_street_address2
  }


  pub fn set_facility_street_address3(&mut self, facility_street_address3: String) {
    self.facility_street_address3 = facility_street_address3;
  }

  pub fn with_facility_street_address3(mut self, facility_street_address3: String) -> FacilityAddress {
    self.facility_street_address3 = facility_street_address3;
    self
  }

  pub fn facility_street_address3(&self) -> &String {
    &self.facility_street_address3
  }


  pub fn set_city(&mut self, city: String) {
    self.city = city;
  }

  pub fn with_city(mut self, city: String) -> FacilityAddress {
    self.city = city;
    self
  }

  pub fn city(&self) -> &String {
    &self.city
  }


  pub fn set_postal_code(&mut self, postal_code: String) {
    self.postal_code = postal_code;
  }

  pub fn with_postal_code(mut self, postal_code: String) -> FacilityAddress {
    self.postal_code = postal_code;
    self
  }

  pub fn postal_code(&self) -> &String {
    &self.postal_code
  }


  pub fn set_address_state_code(&mut self, address_state_code: String) {
    self.address_state_code = address_state_code;
  }

  pub fn with_address_state_code(mut self, address_state_code: String) -> FacilityAddress {
    self.address_state_code = address_state_code;
    self
  }

  pub fn address_state_code(&self) -> &String {
    &self.address_state_code
  }


  pub fn set_address_country_code(&mut self, address_country_code: String) {
    self.address_country_code = address_country_code;
  }

  pub fn with_address_country_code(mut self, address_country_code: String) -> FacilityAddress {
    self.address_country_code = address_country_code;
    self
  }

  pub fn address_country_code(&self) -> &String {
    &self.address_country_code
  }


}



