/* 
 * RIDB API
 *
 * The Recreation Information Database (RIDB) provides data resources to citizens, offering a single point of access to information about recreational opportunities nationwide. The RIDB represents an authoritative source of information and services for millions of visitors to federal lands, historic sites, museums, and other attractions/resources. This initiative integrates multiple Federal channels and sources about recreation opportunities into a one-stop, searchable database of recreational areas nationwide.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct FacilityTour {
  #[serde(rename = "TourID")]
  tour_id: String,
  #[serde(rename = "TourName")]
  tour_name: String
}

impl FacilityTour {
  pub fn new(tour_id: String, tour_name: String) -> FacilityTour {
    FacilityTour {
      tour_id: tour_id,
      tour_name: tour_name
    }
  }

  pub fn set_tour_id(&mut self, tour_id: String) {
    self.tour_id = tour_id;
  }

  pub fn with_tour_id(mut self, tour_id: String) -> FacilityTour {
    self.tour_id = tour_id;
    self
  }

  pub fn tour_id(&self) -> &String {
    &self.tour_id
  }


  pub fn set_tour_name(&mut self, tour_name: String) {
    self.tour_name = tour_name;
  }

  pub fn with_tour_name(mut self, tour_name: String) -> FacilityTour {
    self.tour_name = tour_name;
    self
  }

  pub fn tour_name(&self) -> &String {
    &self.tour_name
  }


}



