/* 
 * RIDB API
 *
 * The Recreation Information Database (RIDB) provides data resources to citizens, offering a single point of access to information about recreational opportunities nationwide. The RIDB represents an authoritative source of information and services for millions of visitors to federal lands, historic sites, museums, and other attractions/resources. This initiative integrates multiple Federal channels and sources about recreation opportunities into a one-stop, searchable database of recreational areas nationwide.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct FacilityActivity {
  #[serde(rename = "ActivityID")]
  activity_id: String,
  #[serde(rename = "FacilityID")]
  facility_id: String,
  #[serde(rename = "ActivityName")]
  activity_name: String,
  #[serde(rename = "FacilityActivityDescription")]
  facility_activity_description: String,
  #[serde(rename = "FacilityActivityFeeDescription")]
  facility_activity_fee_description: String
}

impl FacilityActivity {
  pub fn new(activity_id: String, facility_id: String, activity_name: String, facility_activity_description: String, facility_activity_fee_description: String) -> FacilityActivity {
    FacilityActivity {
      activity_id: activity_id,
      facility_id: facility_id,
      activity_name: activity_name,
      facility_activity_description: facility_activity_description,
      facility_activity_fee_description: facility_activity_fee_description
    }
  }

  pub fn set_activity_id(&mut self, activity_id: String) {
    self.activity_id = activity_id;
  }

  pub fn with_activity_id(mut self, activity_id: String) -> FacilityActivity {
    self.activity_id = activity_id;
    self
  }

  pub fn activity_id(&self) -> &String {
    &self.activity_id
  }


  pub fn set_facility_id(&mut self, facility_id: String) {
    self.facility_id = facility_id;
  }

  pub fn with_facility_id(mut self, facility_id: String) -> FacilityActivity {
    self.facility_id = facility_id;
    self
  }

  pub fn facility_id(&self) -> &String {
    &self.facility_id
  }


  pub fn set_activity_name(&mut self, activity_name: String) {
    self.activity_name = activity_name;
  }

  pub fn with_activity_name(mut self, activity_name: String) -> FacilityActivity {
    self.activity_name = activity_name;
    self
  }

  pub fn activity_name(&self) -> &String {
    &self.activity_name
  }


  pub fn set_facility_activity_description(&mut self, facility_activity_description: String) {
    self.facility_activity_description = facility_activity_description;
  }

  pub fn with_facility_activity_description(mut self, facility_activity_description: String) -> FacilityActivity {
    self.facility_activity_description = facility_activity_description;
    self
  }

  pub fn facility_activity_description(&self) -> &String {
    &self.facility_activity_description
  }


  pub fn set_facility_activity_fee_description(&mut self, facility_activity_fee_description: String) {
    self.facility_activity_fee_description = facility_activity_fee_description;
  }

  pub fn with_facility_activity_fee_description(mut self, facility_activity_fee_description: String) -> FacilityActivity {
    self.facility_activity_fee_description = facility_activity_fee_description;
    self
  }

  pub fn facility_activity_fee_description(&self) -> &String {
    &self.facility_activity_fee_description
  }


}



