/* 
 * RIDB API
 *
 * The Recreation Information Database (RIDB) provides data resources to citizens, offering a single point of access to information about recreational opportunities nationwide. The RIDB represents an authoritative source of information and services for millions of visitors to federal lands, historic sites, museums, and other attractions/resources. This initiative integrates multiple Federal channels and sources about recreation opportunities into a one-stop, searchable database of recreational areas nationwide.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct InlineResponse200Metadata {
  #[serde(rename = "RESULTS")]
  RESULTS: Option<::models::InlineResponse200MetadataResults>,
  #[serde(rename = "PARAMETERS")]
  PARAMETERS: Option<::models::InlineResponse200MetadataParameters>
}

impl InlineResponse200Metadata {
  pub fn new() -> InlineResponse200Metadata {
    InlineResponse200Metadata {
      RESULTS: None,
      PARAMETERS: None
    }
  }

  pub fn set_RESULTS(&mut self, RESULTS: ::models::InlineResponse200MetadataResults) {
    self.RESULTS = Some(RESULTS);
  }

  pub fn with_RESULTS(mut self, RESULTS: ::models::InlineResponse200MetadataResults) -> InlineResponse200Metadata {
    self.RESULTS = Some(RESULTS);
    self
  }

  pub fn RESULTS(&self) -> Option<&::models::InlineResponse200MetadataResults> {
    self.RESULTS.as_ref()
  }

  pub fn reset_RESULTS(&mut self) {
    self.RESULTS = None;
  }

  pub fn set_PARAMETERS(&mut self, PARAMETERS: ::models::InlineResponse200MetadataParameters) {
    self.PARAMETERS = Some(PARAMETERS);
  }

  pub fn with_PARAMETERS(mut self, PARAMETERS: ::models::InlineResponse200MetadataParameters) -> InlineResponse200Metadata {
    self.PARAMETERS = Some(PARAMETERS);
    self
  }

  pub fn PARAMETERS(&self) -> Option<&::models::InlineResponse200MetadataParameters> {
    self.PARAMETERS.as_ref()
  }

  pub fn reset_PARAMETERS(&mut self) {
    self.PARAMETERS = None;
  }

}



