/* 
 * RIDB API
 *
 * The Recreation Information Database (RIDB) provides data resources to citizens, offering a single point of access to information about recreational opportunities nationwide. The RIDB represents an authoritative source of information and services for millions of visitors to federal lands, historic sites, museums, and other attractions/resources. This initiative integrates multiple Federal channels and sources about recreation opportunities into a one-stop, searchable database of recreational areas nationwide.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct PermittedEquipment {
  #[serde(rename = "EquipmentName")]
  equipment_name: String,
  #[serde(rename = "MaxLength")]
  max_length: f64
}

impl PermittedEquipment {
  pub fn new(equipment_name: String, max_length: f64) -> PermittedEquipment {
    PermittedEquipment {
      equipment_name: equipment_name,
      max_length: max_length
    }
  }

  pub fn set_equipment_name(&mut self, equipment_name: String) {
    self.equipment_name = equipment_name;
  }

  pub fn with_equipment_name(mut self, equipment_name: String) -> PermittedEquipment {
    self.equipment_name = equipment_name;
    self
  }

  pub fn equipment_name(&self) -> &String {
    &self.equipment_name
  }


  pub fn set_max_length(&mut self, max_length: f64) {
    self.max_length = max_length;
  }

  pub fn with_max_length(mut self, max_length: f64) -> PermittedEquipment {
    self.max_length = max_length;
    self
  }

  pub fn max_length(&self) -> &f64 {
    &self.max_length
  }


}



