/* 
 * RIDB API
 *
 * The Recreation Information Database (RIDB) provides data resources to citizens, offering a single point of access to information about recreational opportunities nationwide. The RIDB represents an authoritative source of information and services for millions of visitors to federal lands, historic sites, museums, and other attractions/resources. This initiative integrates multiple Federal channels and sources about recreation opportunities into a one-stop, searchable database of recreational areas nationwide.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct RecreationAreaActivity {
  #[serde(rename = "ActivityID")]
  activity_id: String,
  #[serde(rename = "ActivityParentID")]
  activity_parent_id: String,
  #[serde(rename = "RecAreaID")]
  rec_area_id: String,
  #[serde(rename = "ActivityName")]
  activity_name: String,
  #[serde(rename = "RecAreaActivityDescription")]
  rec_area_activity_description: String,
  #[serde(rename = "RecAreaActivityFeeDescription")]
  rec_area_activity_fee_description: String
}

impl RecreationAreaActivity {
  pub fn new(activity_id: String, activity_parent_id: String, rec_area_id: String, activity_name: String, rec_area_activity_description: String, rec_area_activity_fee_description: String) -> RecreationAreaActivity {
    RecreationAreaActivity {
      activity_id: activity_id,
      activity_parent_id: activity_parent_id,
      rec_area_id: rec_area_id,
      activity_name: activity_name,
      rec_area_activity_description: rec_area_activity_description,
      rec_area_activity_fee_description: rec_area_activity_fee_description
    }
  }

  pub fn set_activity_id(&mut self, activity_id: String) {
    self.activity_id = activity_id;
  }

  pub fn with_activity_id(mut self, activity_id: String) -> RecreationAreaActivity {
    self.activity_id = activity_id;
    self
  }

  pub fn activity_id(&self) -> &String {
    &self.activity_id
  }


  pub fn set_activity_parent_id(&mut self, activity_parent_id: String) {
    self.activity_parent_id = activity_parent_id;
  }

  pub fn with_activity_parent_id(mut self, activity_parent_id: String) -> RecreationAreaActivity {
    self.activity_parent_id = activity_parent_id;
    self
  }

  pub fn activity_parent_id(&self) -> &String {
    &self.activity_parent_id
  }


  pub fn set_rec_area_id(&mut self, rec_area_id: String) {
    self.rec_area_id = rec_area_id;
  }

  pub fn with_rec_area_id(mut self, rec_area_id: String) -> RecreationAreaActivity {
    self.rec_area_id = rec_area_id;
    self
  }

  pub fn rec_area_id(&self) -> &String {
    &self.rec_area_id
  }


  pub fn set_activity_name(&mut self, activity_name: String) {
    self.activity_name = activity_name;
  }

  pub fn with_activity_name(mut self, activity_name: String) -> RecreationAreaActivity {
    self.activity_name = activity_name;
    self
  }

  pub fn activity_name(&self) -> &String {
    &self.activity_name
  }


  pub fn set_rec_area_activity_description(&mut self, rec_area_activity_description: String) {
    self.rec_area_activity_description = rec_area_activity_description;
  }

  pub fn with_rec_area_activity_description(mut self, rec_area_activity_description: String) -> RecreationAreaActivity {
    self.rec_area_activity_description = rec_area_activity_description;
    self
  }

  pub fn rec_area_activity_description(&self) -> &String {
    &self.rec_area_activity_description
  }


  pub fn set_rec_area_activity_fee_description(&mut self, rec_area_activity_fee_description: String) {
    self.rec_area_activity_fee_description = rec_area_activity_fee_description;
  }

  pub fn with_rec_area_activity_fee_description(mut self, rec_area_activity_fee_description: String) -> RecreationAreaActivity {
    self.rec_area_activity_fee_description = rec_area_activity_fee_description;
    self
  }

  pub fn rec_area_activity_fee_description(&self) -> &String {
    &self.rec_area_activity_fee_description
  }


}



