/* 
 * RIDB API
 *
 * The Recreation Information Database (RIDB) provides data resources to citizens, offering a single point of access to information about recreational opportunities nationwide. The RIDB represents an authoritative source of information and services for millions of visitors to federal lands, historic sites, museums, and other attractions/resources. This initiative integrates multiple Federal channels and sources about recreation opportunities into a one-stop, searchable database of recreational areas nationwide.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct TourMembertours {
  #[serde(rename = "MemberTourID")]
  member_tour_id: i32
}

impl TourMembertours {
  pub fn new(member_tour_id: i32) -> TourMembertours {
    TourMembertours {
      member_tour_id: member_tour_id
    }
  }

  pub fn set_member_tour_id(&mut self, member_tour_id: i32) {
    self.member_tour_id = member_tour_id;
  }

  pub fn with_member_tour_id(mut self, member_tour_id: i32) -> TourMembertours {
    self.member_tour_id = member_tour_id;
    self
  }

  pub fn member_tour_id(&self) -> &i32 {
    &self.member_tour_id
  }


}



