/* 
 * RIDB API
 *
 * The Recreation Information Database (RIDB) provides data resources to citizens, offering a single point of access to information about recreational opportunities nationwide. The RIDB represents an authoritative source of information and services for millions of visitors to federal lands, historic sites, museums, and other attractions/resources. This initiative integrates multiple Federal channels and sources about recreation opportunities into a one-stop, searchable database of recreational areas nationwide.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct Zone {
  #[serde(rename = "PermitEntranceZoneID")]
  permit_entrance_zone_id: String,
  #[serde(rename = "Zone")]
  zone: String
}

impl Zone {
  pub fn new(permit_entrance_zone_id: String, zone: String) -> Zone {
    Zone {
      permit_entrance_zone_id: permit_entrance_zone_id,
      zone: zone
    }
  }

  pub fn set_permit_entrance_zone_id(&mut self, permit_entrance_zone_id: String) {
    self.permit_entrance_zone_id = permit_entrance_zone_id;
  }

  pub fn with_permit_entrance_zone_id(mut self, permit_entrance_zone_id: String) -> Zone {
    self.permit_entrance_zone_id = permit_entrance_zone_id;
    self
  }

  pub fn permit_entrance_zone_id(&self) -> &String {
    &self.permit_entrance_zone_id
  }


  pub fn set_zone(&mut self, zone: String) {
    self.zone = zone;
  }

  pub fn with_zone(mut self, zone: String) -> Zone {
    self.zone = zone;
    self
  }

  pub fn zone(&self) -> &String {
    &self.zone
  }


}



